apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-8kfg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0022-tenant/tkrw-pr712-0075-0022-app/devfile-sample-8kfg@sha256:3b3ae2b52812a353e22f638b834490a376253c1186690a0fd3041f5ad2ef5e5c
        name: my-nodejs
        resources: {}
status: {}
